services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: npm run start:dev admin
    env_file:
      - ./apps/admin/.env
    depends_on:
      - auth
      - db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - rabbitmq
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    ports:
      - '3002:3002'
    env_file:
      - ./apps/payments/.env
    depends_on:
      - db
      - rabbitmq
      - admin
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  wallets:
    build:
      context: .
      dockerfile: ./apps/wallets/Dockerfile
      target: development
    command: npm run start:dev wallets
    ports:
      - '3003:3003'
    env_file:
      - ./apps/wallets/.env
    depends_on:
      - db
      - rabbitmq
      - payments
      - admin
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  mongodb_master_data:
    driver: local